### ISSUE TITLE
刚刚在nga看到的，原贴已被锁隐。

### ISSUE THREAD

**Issue by InahoKaede** [Trojblue/Genshin-Bible#4]
![i2Q5-hej4ZbT3cSkj-sg jpg medium](https://user-images.githubusercontent.com/72701863/95683418-a662a680-0c1d-11eb-9004-2dafe483866d.jpg)
![i2Q5-257xK14T3cSu0-87 jpg medium](https://user-images.githubusercontent.com/72701863/95683423-af537800-0c1d-11eb-896f-fa1fb1e8c1dd.jpg)
![i2Q5-49h0ZcT3cSu0-e4 jpg medium](https://user-images.githubusercontent.com/72701863/95683426-b37f9580-0c1d-11eb-9d33-75b634a9476d.jpg)
![i2Q5-4wq9ZcT3cSu0-l2 jpg medium](https://user-images.githubusercontent.com/72701863/95683431-b7131c80-0c1d-11eb-85c9-9bdaa828be7f.jpg)
![i2Q5-6nwuZcT3cSu0-he jpg medium](https://user-images.githubusercontent.com/72701863/95683435-bb3f3a00-0c1d-11eb-82b9-d8aae66106d5.jpg)

**Comment by trojblue** [comment]
已加入圣经全家桶
