### ISSUE TITLE
《内心浮躁》

### ISSUE THREAD

**Issue by dkswxd** [Trojblue/Genshin-Bible#6]
那么问题来了，到底是游戏资源给少了，还是玩家自己内心太浮躁了？
以前砍传奇的年代好几天，甚至半个月升一级，玩家觉得好难升，但是不会去骂游戏给的经验太少。
但是现在呢？
动不动就是蚊子腿，没体力，CH抠，这个游戏上来给你60级好不好，有什么意义呢？有乐趣的不就是一点点变强的过程吗？
每天积累一点点，一个月下来，你就甩开了比你更加懈怠的那些人很多很多了，氪金都追不上你的那种，这不很好吗？

非要去和隔壁游戏比，上次还看到个大哥拿原神的圣遗物去和阴阳师的御魂比较，到底有没有点脑子，原神要是学阴阳师的御魂，游戏早就黄了，0氪一辈子都没办法和大佬在论坛PVP，阴阳师直接卖御魂的好嘛？30块钱一个，黑了心的游戏也配和我原神比较？
再说蚊子腿，哪个手游的福利又不是蚊子腿了，你找一个不是的我瞧瞧，不论活动福利再丰富，最后到了玩家手上都是10分钟用光，自己想想把。

https://bbs.nga.cn/read.php?&tid=23708785&pid=459280212

**Comment by trojblue** [comment]
感谢，已加入全家桶

**Comment by TangleZ** [comment]
interesting。
