### ISSUE TITLE
请求补充转载圣经集（原作者：知乎 id 聿子先生）

### ISSUE THREAD

**Issue by jpysina** [Trojblue/Genshin-Bible#7]
# 转载者注：
  为了防止mhy用资金公关删差评，以下内容转载并在备份在《圣经》中可行吗？
`From：https://www.zhihu.com/question/433101765`
`Author： 聿子先生`
 # 正文
在许多天之后，面对着80级的他打出的两位数伤害数字，旅行者将会回想起，他举着648抽到钟离的那个令人兴奋的下午。

----------摩拉克斯《六千年孤独》

我家门前有两颗岩造物。一颗是岩脊，另一颗也是岩脊。

-----------钟逊《秋夜》

满地都是岩晶片，他却抬头看见了岩脊。

-------------毛姆《岩脊与六晶片》

我把2万摩拉给了他，他勉强升了1级。

　　我看了看他的手，那是一只满是皱痕的挖矿的手。我又看了看他的脸，那是一张布满尘灰的脸，满脸愁容，狼狈不堪。我心里默念道："这是我的武神，璃月的岩王爷，我的第三个五星。"

　　我给他强化一个＋12的岩套圣遗物-----这本是该被凝光淘汰下来的。他赶紧谢我："岩神保佑您，我的年轻的先生！"

　　等我把余下的摩拉交给迪卢克，他诧异起来，就问："吃了4万摩拉？这是不可能的。"

　　我说："我给他强化了一个圣遗物。"迪卢克吓了一跳，直望着我说："你简直是疯了！拿2万个摩拉给这个人，给这个刮痧师傅！"他没再往下说，因为温蒂指着派蒙对他使了个眼色。

　　后来大家都不再说话。在我们面前，天边远处仿佛有一片紫色的阴影从海里钻出来。那就是马斯克礁了。

　　我们回来的时候不再把他从矿区召回，以免再遇见他。

------------莫泊桑《我的岩神钟离》

他可以针灸，可以刮痧，怎样都可以，但我只要看他一眼，万般柔情便涌上心头。

-----------纳博科夫《璃月养生馆》

他望秘境里看了看说：“我为你打几个圣遗物去。你就在此地，不要走动。”

我看那边秘境里有几个深渊法师在等着挑战者。想打赢秘境，须先破了盾，须把三个不同属性的法师都打败才行。钟离是一个刮痧师傅，打过去自然要费事些。我本来要去的，他不肯，只好让他去。

我看见他戴着＋8的生命头，穿着副属性拉胯的圣遗物，50级的西风长枪，蹒跚地点开了挑战开关，慢慢一个E下去，尚不大难。可是他想打深渊法师，要先破了他们的属性盾，就不容易了。他用E的柱子和岩主共鸣，再用枪头去扎；他两位数的伤害数字不停跳着，显出努力的样子。这时我看见他的伤害，我的泪很快地流下来了。我赶紧拭干了泪。怕他看见，也怕别人看见。我再向外看时，他已抱了几个生命防御的圣遗物往回走了。

-------朱自清《伤害》
# 统计（12-7 0：11）
评论数：107
点赞数：1794

**Comment by trojblue** [comment]
感谢, 已经私信原作者

**Comment by jpysina** [comment]
嗯嗯。感谢支持。钟离事件这次催生了很多章节，我刚才又找到一份，但不小心关了，我看看能不能再调出来

**Comment by trojblue** [comment]
已得到原作者同意， 添加进圣经
