### ISSUE TITLE
再次补充转载本次那个男人事件派生出的新章节

### ISSUE THREAD

**Issue by jpysina** [Trojblue/Genshin-Bible#8]
# 转载者注
保护我方成员，人人有责。
>link [https://www.zhihu.com/people/kenssa](https://www.zhihu.com/people/kenssa)
>author `碓氷千企`
>article [《原神》的风评是如何“转变”的？
>3098👍303评
](https://www.zhihu.com/question/420330765)

注：如果允许转载，请关闭本issue以便告知哈
# 目标转载内容（有部分内容已收录）
>WARING 虽说是高质量内容原贴带有嵌套和高级格式，建议还是询问一下转载权比较好
>**似乎已有重复内容。请注意，可能存在交叉引用**

六、假设你叫李华，是一个年轻的中国玩家。你的外国笔友Tony Ma给你写信，提到一款名为《原神》的高分中国游戏，想征求你的意见。
请你在metacritic上，留下你的差评，开头评分以给出，不计入字数。内容要点如下：
1.这款游戏是换皮缝合（9个月前）；
2.这款游戏是抄袭作品（6个月前）；
3.这款游戏抄的不合格（3个月前）；
4.这款游戏在碰瓷营销（现在）。
注意：
1.短文必须包括所有内容要点，可适当发挥；
2.词数：100左右。
3.参考词汇：genshin 原神、copy 抄袭、touch porcelain 碰瓷、brahmin 婆罗门
0/10
————《提瓦特世界留学统一考试五年真题作文专项训练 ·  其一》 MHY出版社 2020-12月版`申请转载者拟题`

乐经·旧约 历国记 第1章 第1段

“肯定暴毙”
“三个月暴毙”
“先活三年再说”
“流水不如王者荣耀的垃圾”
“什么时候不承认是爆款了？爆款一样是垃圾”
——节选自《巴黎报刊大全·上》
乐经·旧约 历国记 第1章 第2段

“只会抄外国的垃圾，出国肯定被骂到暴毙”
“丢人丢到外国去了”
“外国佬都收钱了才给高分”
“外国佬看你免费才给高分”
“外国那给的也不算什么高分”
——节选自《巴黎报刊大全·下》
乐经·旧约 历国记 第2章 第1段

国外评价低，垃圾游戏丢脸丢到国外去了。
国外评分高，垃圾测评平台连个游戏都不会看。
——节选自《抵抗全敌·上》
乐经·旧约 历国记 第2章 第2段

国外媒体没点评原神。你居然不知道全媒体给满分的荒野之息，可笑。
国外媒体点评原神之后。这些媒体连美末2都给满分，原神9分就是堪比美末2。
——节选自《抵抗全敌·下》
乐经·旧约 历国记 第3章 第1段

原神居然在外用罗马音，而不是汉语拼音，原神果然是日本游戏，不是国产游戏。——节选自《逻辑学·上》
乐经·旧约 历国记 第3章 第2段

别跟我扯什么米卫兵，你敢扯我就敢说你慕日犬。——节选自《逻辑学·下》
乐经·旧约 历国记 第4章 第1段

“任何一个玩mihoyo游戏的全家生生世世中国人永远不得轮回国外。”——节选自《福报》
乐经·旧约 历国记 第4章 第2段

“璃月地区的建筑大部分是日式风格的唐破风，mhy果然是日本公司。”
“《黑神话悟空》也一样，也是唐破风这种日式建筑。”
“胡说！”
——节选自《华夷之辩》
乐经·旧约 历国记 第4章 第3段

原神上架switch，老任恰烂钱。
原神上架ps4，索尼恰烂钱。
IGN9分，IGN恰烂钱。
Fami通白金，Fami通恰烂钱。
——节选自《资本主义》
乐经·旧约 历国记 第4章 第4段

我看外国的朋友们对原神评价更理性些最少不像国内云玩家一下我也不行黑自己国产的作品去吹别国的游戏——节选自《阿巴阿巴》
乐经·旧约 历国记 第4章 第5段

国外评分机构和玩家对《原神》这种游戏的追捧，是不是把中国游戏带上邪路的阴谋？——节选自《十面埋伏》
乐经·旧约 历国记 第4章 第6段

纯路人，见不得国产之光好是吧？——节选自《名人名言大全》

乐经·旧约 任书 第1章 第1段

什么年度最佳的3A大作画面比不上欧美普通3A?
因为掌机机能限制。
为什么掌机玩两个小时就没电了?
可以插底座连电视玩啊。
为什么连电视我不用性能更好的其他主机呢?
你那些垃圾主机能拿在手里当掌机玩吗?
——节选自《立体防御理论·上》
乐经·旧约 任书 第1章 第2段

塞尔达有，原神没有的就是垃圾；
塞尔达有，原神也有就是垃圾抄袭；
塞尔达没有，原神有的就是随意添加垃圾；
塞尔达有，原神也有但是和塞尔达不同的就是抄都抄不会。
——节选自《立体防御理论·中》
乐经·旧约 任书 第1章 第3段

电脑游戏，手机当然不能要求画质，
手机游戏，电脑当然不能要求质量。
单机游戏，玩家当然不能要求社交，
网络游戏，氪金当然不能要求良心。
——节选自《立体防御理论·下》
乐经·旧约 任书 第2章 第1段

为什么jc一个月就漂移了?因为刚出，以后就好了。
都2019年了怎么还没解决手柄漂移问题?国行要上了，建议买国行配件保修。
听说ns要出Pro了，手柄问题能解决吗？
能，说不定换代还能跑4k呢。
——节选自《为了更美好的明天·上》
乐经·旧约 任书 第2章 第2段

为什么玩法这么空洞？
一测：“这才一测，以后肯定会好的”
为什么玩法这么空洞？
二测：“这才二测，以后肯定会好的”
为什么玩法这么空洞？
三测：“这才三测，以后肯定会好的”
为什么玩法这么空洞？
公测：“这游戏刚出，以后肯定会好的”
——节选自《为了更美好的明天·下》
乐经·旧约 任书 第3章 第1段

“原神抄塞尔达”
“抄还抄不像”
——节选自《薛定谔·上》
乐经·旧约 任书 第4章 第1段

为什么旷野之息这么好玩的游戏也会有人不喜欢玩?
因为他没玩到入门，我玩到入门之后就根本停不下来。
原神这么垃圾怎么还有人玩?
我玩了挺好的呀，玩到璃月感觉设计的越来越好了。
这么垃圾，好个屁，配让我下载?
——节选自《胜者思维·上》
乐经·旧约 任书 第4章 第2段

35级都没有也出来乱黑？
都玩到35级了还在这黑是不是贱？
不玩就卸载啊瞎黑什么？
——节选自《胜者思维·下》
乐经·旧约 任书 第5章 第1段

别再扯什么抄袭了，是原神带火了塞尔达!小众机型小众游戏，因为一大厂手游被顶.上热搜，然后周围有几个同学都想去玩玩试试，之前压根就没听说过这游戏，这应该就是大厂的周边效应吧。
——节选自《荒诞故事·上》
乐经·旧约 任书 第5章 第2段

恕我直言我无知，在原神出来前我都没听说过塞尔达，别跟我扯塞尔达多牛多牛。
——节选自《荒诞故事·下》
乐经·旧约 任书 第5章 第3段

兄弟，一看你就没玩过几个游戏，我虽然也没啥钱，但steam上还是有几个游戏的，我把我steam号借你，你玩玩塞尔达，让你见识一下什么叫真正的游戏。——节选自《科幻世界·下》
乐经·旧约 任书 第6章 第1段

我任天堂游戏厂商所以游戏性比机能更重要。
我任天堂是卖游戏机的所以游戏机再差第一方游戏都永远独占。——节选自《双面人·上》
乐经·旧约 任书 第6章 第2段

原神是国产游戏所以你们要容忍我抄袭和氪金。
原神是世界游戏所以我不过中国节日。
——节选自《双面人·下》
乐经·旧约 任书 第7章 第1段

游戏质量中国手游顶端,pc中名列前茅，中等偏.上水平3a以前吹得太过了,被嘲笑，现在正常等7个国家出完那就是世界顶尖3A水平，不可能不超过荒野之息的。——节选自《梦的解析·下》
乐经·旧约 任书 第7章 第2段

巫师3是RPG游戏的集大成者。能玩到很多游戏的玩法，甚至还能打牌。
塞尔达传说重新定义开放世界，制作人表示从育碧游戏中学习到了很多。
原神——抄袭，缝合怪。
——节选自《严以律己》
乐经·旧约 任书 第7章 第2段

BOTW事RPG；原神也事RPG。
BOTW2017年发布；原神也事2017年立项。
BOTW成本1e刀；原神成本也事1e刀。
BOTW一周回本；原神也事一周回本。
BOTW上了NS；原神也要上NS。
BOTW广受外国玩家好评，事鉴作；原神也广受外国玩家好评，事鉴作。
BOTW有最好的开放世界，事王道征途；原神有中国最好的开放世界，也事王道征途。
任天堂有很多狂热的粉丝，事偶像；米哈游也有很多狂热的粉丝，也事偶像。
任天堂既事民间高手也事黑暗任天堂，具备屑鉴二象性；米哈游既事国产之光也事黑暗骑士，也具备屑鉴二象性。

数字论证：
原神=10+9；ゼルダの伝説 ブレス·オブ·ザ·ワイルド=9+1-6+14-12+13
19=19
Q. E. D.
——《原神BOTW说》

乐经·旧约 箴言 第1章 第1段

原神发布那天是国产游戏最黑暗的一天。抄袭游戏都好意思出?随便一个国产手游都能吊打他，还敢上全平台，丢人！原神教坏r星、育碧、cdpr、索尼、任天堂，他们五个都学坏了，穿越时空回到几年前做内购游戏。
——节选自《超时空战警·上》
乐经·旧约 箴言 第1章 第2段

“《原神》画风是对《塞尔达传说：荒野之息》（2017）的劣拙模仿。恶心”
“《原神》画风跟《崩坏3》（2016）相比没有进步。垃圾”
——节选自《超时空战警·下》
乐经·旧约 箴言 第2章 第1段

你否定原神的画面就是在否定u3d开发的全部游戏，笑死了。——节选自《假如给我三天光明·上》
乐经·旧约 箴言 第2章 第2段

原神老老实实在手机上待着不行吗?这质量好意思上PC和主机?能和PC游戏和主机游戏比?——节选自《假如给我三天光明·下》
乐经·旧约 箴言 第2章 第3段

“原神技术比黑神话领先16年，如果原神不叫3A，黑神话就没资格叫3A了。”——节选自《梦的解析·上》
乐经·旧约 箴言 第2章 第4段

米哈游要靠原神成为中国第三游戏公司了吧，少说一年盈利300亿，这么大的盈利不得不***,这也是用心做游戏的结果，互利共赢，任天堂，索尼一年赚的到这么多钱吗？——节选自《科幻世界·上》
乐经·旧约 箴言 第3章 第1段

原神不能把角色设定成内购的吗？
——节选自《元气骑士之殇》
乐经·旧约 箴言 第3章 第2段

原神就不能学习一下古剑三搞买断制吗？
——节选自《烛龙兴衰史》
乐经·旧约 箴言 第3章 第3段

原神要是买断制，少卖点钱，以后卖dlc不行吗？
——节选自《不存在的p社中国》
乐经·旧约 箴言 第3章 第4段

帕斯卡契约四十五块钱能玩到所有内容，原神行吗？
——节选自《TipsWorks：破瓜之痛》
乐经·旧约 箴言 第3章 第5段

原神就不能……
你是不是闲的，去买《嗜血印》，那才是真正的国产巅峰。
——节选自《国产之光·新编》

乐经·旧约 箴言 第3章 第6段

原神，抄袭！垃圾！
天涯明月刀，启动！
——节选自《罪与罚》
乐经·旧约 箴言 第4章 第1段

“855卡顿，A12卡顿，都是手机不好在尬黑。”来自vivo Y85A（高通骁龙450）
——节选自《手机》
乐经·旧约 箴言 第4章 第2段

就算以300w份算，一份只卖200rmb，那就是6亿人民币了，更别说还有什么黄金版啊典藏版啊珍藏版啊什么的，到时候再搞几个dlc卖卖副本皮肤，扣掉渠道分成也回本了。——节选自《高等数学》
乐经·旧约 箴言 第5章 第1段

公测前:原神1亿美刀花了1千万做宣发
开服前:原神1亿美刀花了5千万做宣发
开服后:原神1亿美刀花了9千万做宣发
——节选自《千万小心》
乐经·旧约 箴言 第5章 第2段

2019年知乎评分25%，9月15日35%，10月36%，11月39%。——节选自《千万级宣发》
乐经·旧约 箴言 第6章 第1段

如果你认为原神是腊鸡而拿不到金摇杆奖，游戏表现不如原神的其他国产游戏便是腊鸡不如；如果你认为有不少优质国产游戏，那么不得不承认原神也是一款优质游戏。——原神第一悖论
乐经·旧约 箴言 第6章 第2段

如果你认为TGA是给钱就能上的野鸡奖，没有权威性，那么其他获奖的游戏也存在给钱买奖的嫌疑，并且获奖的含金量将会大量贬值；如果你认为TGA是个比较中肯且具有一定权威的奖项，那么你不得不承认获得TGA奖项的原神的确有可圈可点之处。——原神第二悖论
乐经·旧约 箴言 第6章 第3段

如果你认为原神是一个腊鸡，那么金翎奖就是最权威的奖项，因为它让原神空手而归，但这样你就不得不承认王者荣耀是最佳原创移动游戏；如果你否认王者荣耀是最佳原创移动游戏，那么你不得不承认金翎奖毫无权威可言，原神没有获奖反而说明了并没有花钱买奖。——原神第三悖论
乐经·旧约 箴言 第7章 第1段

碰到一切mh首先默认其为正在进行黑红战略的mwb——最高指示

乐经·新约 使徒行转 第1章 第1段

他们都没玩过______。但凡他们玩过______就都会知道，有______这座翻越不过的高山，任何关于游戏的争论都毫无意义。只有垃圾游戏才会去抄袭别人，只有垃圾游戏才会在意被人抄袭。
______，一个根本不介意被人抄袭，也不介意被人模仿的艺术！如果说游戏是第九艺术的话，那么______就是第十艺术。但凡他只要玩过，玩过，听说过_____，眼里就放不下任何游戏了！
——节选自《说八股》
乐经·新约 使徒行转 第2章 第1段

“啊，不会有人觉得这游戏不良心吧？我一0氪十连三个五星，我觉得这游戏不错啊，不知道你们为啥瞎黑。”——节选自《吾即世界》
乐经·新约 使徒行转 第2章 第2段

“没有五星，打不过。逼课”
太简单了，毫无难度。无聊
——节选自《薛定谔·下》
乐经·新约 使徒行转 第2章 第3段

“游戏尬黑的太多，氪金和游戏卡怎么能怪游戏？游戏要求的配置高怪游戏吗？氪金很黑是你自己氪不过别人来给游戏打一星。”——节选自《七宗罪》
乐经·新约 使徒行转 第2章 第4段

“低价买廉价负面热搜的操作过于频繁”
“米哈游吃相太难看了，可以看到很多卫兵言论”
“从未有组织故意抹黑原神，一切都是mhy买水军反串搞负面营销”
——节选自《光速绕树》
乐经·新约 使徒行转 第3章 第1段

虽然王者荣耀也抄风暴lolDOTA，为啥骂的人为啥比还原神作少一些呢？因为王者荣耀不是人均卫兵，而且也没米哈游那么贪婪。——节选自《抄袭、卫兵与贪婪：中国游戏公司的命运》
乐经·新约 使徒行转 第3章 第2段

“为什么你批判mihoyo玩家？”
“因为我怀疑他们搞饭圈化。”
“为什么你不批判NS、PS4、xbox玩家？”
“因为他们真的是饭圈。”——节选自《美国笑话选》
乐经·新约 使徒行转 第4章 第1段

“十问《检察日报》、十问《光明日报》、十问《解放日报》”
“原神只是国内每年那么多换皮工业垃圾游戏的其中一个，但米卫兵已经成为游戏届肖战粉般可怕的生物了”
“驻意大利大使馆敢发原神？xdm冲了冲了”
——节选自《Who am I？》
乐经·新约 使徒行转 第5章 第1段

这些都是米卫兵中的nt,把nt的话来大作文章，反复考究，甚至出版成册，比做圣经。已经成nt教的神官了，继续传播你的教条给nt听吧。——节选自《大清洗》
乐经·新约 使徒行转 第5章 第2段

比米卫兵圣经点赞少太多了
对线味浓娱乐味少
而且很多话压根没见米黑提过
两边都有极端
但卫兵多的多——节选自《信息茧房》
乐经·新约 使徒行转 第5章 第3段

请选择你的英雄！
A 米卫兵
B 米黑
C 纯路人
D 理中客
E 天龙人
F 乐子人
——《Genshin Impact-Multiplayer》

乐经·新约 启示录 第1章 第1段

塞尔达120神庙全通，明天cj我就不去了，怕认错展台。——节选自《贼喊捉贼》
乐经·新约 启示录 第2章 第1段

原神，碰瓷营销。——节选自《关于“比附营销”一词的再定义》
用微量炸药定向爆破拔牙（智齿）应该分几步，如何具体操作，有什么需要注意的？——节选自《黑红营销》

乐经·新约 犹大书 第1章 第1段

如何评价米哈游的新游戏《原神》pv抄袭《塞尔达传说》pv?

如何看待Mihoyo公司新作《原神》的“美术风格”疑似抄袭《塞尔达传说：荒野之息》？

如何评价米哈游新作《原神》开测的实际玩法画面与《塞尔达》的相似？

乐经·新约 犹大书 第1章 第2段

《原神》是否对塞尔达构成抄袭？

如何有力证明原神是抄袭塞尔达的？

乐经·新约 犹大书 第1章 第3段

原神抄袭了多少游戏？

《原神》抄袭其他游戏，有哪些证据？

我是原神玩家，没有玩过塞尔达，请问原神抄袭的地方有哪些呢？

乐经·新约 犹大书 第2章 第1段

真正的的塞尔达玩家对米哈游《原神》的看法是怎样的？

米哈游继续做游戏的话，能对中国游戏市场造成怎样的影响？

原神是不是会成为国产游戏最黑暗的一天？

原神会不会成为中国游戏历史的一个黑暗点.原神的赚了大钱导致行业风向变化，所有单机游戏全改成这个模式？

乐经·新约 犹大书 第2章 第2段

如何看待米哈游总裁刘伟披露《原神》的研发投入已达1亿美元？

如何看待米哈游总裁刘伟称「原神研发投入达 1 亿美元，在欧美是难以想象的」?

如何评价米哈游员工分析《原神》在制作技术和难度上高于《黑神话：悟空》？

乐经·新约 犹大书 第3章 第1段

如果mihoyo新作《原神》在发布后被洗白，你会怎么看待这个事件?

乐经·新约 犹大书 第4章 第1段

如何看待 9 月 15 日《原神》PC 端不删档测试？

乐经·新约 犹大书 第4章 第2段

为什么现在没人骂原神抄袭了?

为什么现在没有人指责原神了呢？

为什么会有那么多人为游戏《原神》洗地呢？

乐经·新约 犹大书 第4章 第3段

如何看待FAMI通给原神35分白金殿堂？

如何评价IGN给《原神》9分，而同时间的《博德之门》7分?

怎么看待《原神》在海外的风评和口碑与国内的巨大差异？

乐经·新约 犹大书 第4章 第4段

抛开米哈游自己的操作，尬吹原神的人真的很多吗？

我觉得原神非常非常好玩，但是在网上几乎都是喷原神的，是我游戏的品味太低吗？

为什么《原神》在知乎的游戏评分这么低？

乐经·新约 犹大书 第5章 第1段

朋友不听劝坚持玩原神该怎么办?

原神到底花了多少钱搞公关？

乐经·新约 犹大书 第5章 第2段

《原神》在业界看来真的很成功吗？

米哈游的这套模式，真的不值得其他厂商学习吗？

原神的质量真的碾压大部分国产开放世界手游吗？

承认原神在全球多平台非常优秀很难吗？

批判《原神》这款游戏的所谓业内人士，他们的作品是怎样的游戏？

乐经·新约 犹大书 第5章 第3段

如何评价《原神》被2020年金摇杆奖提名?

如何看待2020年金摇杆年度最佳游戏奖《原神》以第二名成绩败于《最后的生还者2》？

如何评价游戏《原神》获得TGA 2020年度最佳移动游戏和最佳RPG游戏提名？

如何看待《原神》获得App Store 和Google Play年度游戏，成为中国首款年度精选app？

乐经·新约 犹大书 第6章 第1段

如何评价游戏《原神》中“中原杂碎”菜名让部分玩家不适？

如何评价《原神》疑似在新活动中暗讽国外疫情？

如何看待原神歧视国内玩家?

原神中国风地区的神角色钟离由于过于弱，被外国玩家称为 “病夫”，你怎么看？

乐经·新约 犹大书 第6章 第2段

原神和李子柒，哪个是更好的文化输出?

原神是不是中国第一个产生大范围文化输出的「手机游戏作品」？

国外评分机构和玩家对《原神》这种游戏的追捧，是不是把中国游戏带上邪路的阴谋？

**Comment by trojblue** [comment]
收到, 这个也给原作者发私信了, 哈哈

**Comment by jpysina** [comment]
嗯嗯谢啦老哥

**Comment by trojblue** [comment]
已添加, 晚了点不好意思
