### ISSUE TITLE
建议加一点米黑圣经，或者说叫黑暗圣经？

### ISSUE THREAD

**Issue by ccccxxx** [Trojblue/Genshin-Bible#9]
作者：睿智的清洁工
链接：https://www.zhihu.com/question/426769861/answer/1608444406
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

"原神你不充钱大佬一天杀你几百次你都不能还手，还没pvp呢#(笑眼)  "-------节选自《PVP》

"出自ign评测视频，648首充还在就满角色，这河里吗"-------节选自《传统洗地文学大赏》

"崩三几个大学生俩月就能做出来，米卫兵还自以为多难呢#(捂嘴笑)  "------节选自《大学生》

"哈哈哈哈哈，恰烂钱好讽刺，那是海拉鲁的大好河山谢谢！"------节选自《2020割让张家界协议》

"所以天朝只有这种骗钱游戏，把塞尔达代码修修改改就拿出来的垃圾。"------节选自《代码抄袭》

"如果app版链接了推特账号，人家还可以删除你的好友和推文，还可以发送推文。"------节选自《米哈游8级文明操控全世界》

"米孝子天天吹米哈游技术力，又说腾讯打压米哈游，差不多得了#(哈哈)  ，论辈分，腾讯是你们爷爷。"------节选自《认亲》

"你玩原神，你马出门被qj，享受被女干杀。"-------节选自《当代巫术大全》

"怕不是到时候china封杀mhy你都能跟china干起来？#(吐舌)  你们到底是china人还是米国人还用说吗？"------节选自《开除国籍》

"也不知道是做的什么打算你们这几天老看日本玩家的评分，不会准备举国搬到那里去吧"------节选自《开除国籍2》

"原博几天都没删，我早上转一下十分钟就被公关了？真是大公司啊手眼通天，害怕。"------节选自《十分钟出警》

"玩了20分钟不到卸载了，纯属吹j8"------节选自《2020/9/13》

"兄弟们，架可以打，酒可以喝，烟可以抽，但是你玩原神，对不起，你没有妈妈"------节选自《猎马人》

"玩米哈游游戏的都是傻口"------节选自《日常》

"拿一个抄袭日本游戏塞尔达原神来宣传？不知道的别人以为我们14亿人还不如人家一个岛国的人，你也配代表中国？发这条推的人死在意大利得了"------《轰炸大使馆2020年内战版限定》

**Comment by ccccxxx** [comment]
这里还有个写的比你全的，两方面都记录了。

《原神》的风评是如何“转变”的？ - 碓氷千企的回答 - 知乎
https://www.zhihu.com/question/420330765/answer/1545911391

**Comment by trojblue** [comment]
收到, 感谢提供

> 作者：睿智的清洁工
> 链接：https://www.zhihu.com/question/426769861/answer/1608444406
> 来源：知乎
> 著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
 
这条去私信原作者了

> 《原神》的风评是如何“转变”的？ - 碓氷千企的回答 - 知乎
> https://www.zhihu.com/question/420330765/answer/1545911391

这条在#8 有提到, 已经拿到许可了, 就是内容比较多, 还没编辑好贴上去

我现在在考虑把"文学性内容"和mwb/米黑的真实发言分开变成两个条目, 这样更清楚一点

**Comment by jpysina** [comment]
确实，从9月15号开服以来，舆论中圣经的风格有很多种。比如说反讽MWB的，讽刺角色的，讽刺MHY的。如果直接扔进来是不是会引发风格混乱？分卷处理会不会更好，比如说每卷一种风格，统一针对一种对象。
ps.我感觉前几天我抓的几个钟离的好像“污染了原来的圣经风格”😂

**Comment by trojblue** [comment]
>分卷处理会不会更好，比如说每卷一种风格，统一针对一种对象。

是这个打算, 等有空就多搞几卷, 这样观感也好一点, 不会一次一大长页

> ps.我感觉前几天我抓的几个钟离的好像“污染了原来的圣经风格”😂

哈哈 这不至于, 内容当然是越多越好 只要后面能分好就行 本来能发issue提供内容就很感谢了😂

**Comment by trojblue** [comment]
已添加
